apiVersion: v1
kind: PersistentVolume
metadata:
 name: svn
spec:
 capacity:
  storage: 100Mi
 accessModes:
  - ReadWriteOnce
 storageClassName: slow
 hostPath:
  path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/registry/csw-config-svn